### ISSUE TITLE
add support for atomic rename in R2

### ISSUE THREAD

**Issue by djouallah** [delta-io/delta-rs#1356]
add support for atomic rename in R2

**Comment by cmackenzie1** [comment]
There is a dependency on having it supported in the upstream `object_store`crate. After it is added there then it can be added here. 

https://github.com/apache/arrow-rs/issues/4190

**Comment by djouallah** [comment]
great, it is seems it is done upstream, what's next

**Comment by djouallah** [comment]
@cmackenzie1 any updates ?

**Comment by kvap** [comment]
Should I create a PR with that change? (disabling S3LockError::LockClientRequired)

**Comment by cmackenzie1** [comment]
> Should I create a PR with that change? (disabling S3LockError::LockClientRequired) I am not completely sure if it is the right way.

I think adding it as an optional config value + defaulting to `S3LockError::LockClientRequired` if not specified would be best.

**Comment by djouallah** [comment]
How do you do that using the Python API ?

**Comment by roeap** [comment]
> I think adding it as an optional config value + defaulting to S3LockError::LockClientRequired if not specified would be best.

@cmackenzie1 - While working on leveraging more of object-stores's features in #1592, I added a simple check for the `AmazonS3ConfigKey::CopyIfNotExists` option, and if it exists, we avoid wrapping the object store with the lock clients stuff from our crate. I think that should fix it?

**Comment by cmackenzie1** [comment]
@roeap I don't think there is any specific reason we are using the wrapper - probably just using it because it is there. Looking at the code for the wrapper, it doesn't look like it adds much value over `object_store` crate version.

**Comment by djouallah** [comment]
still the same error ? using Python 0.11 ? 

`_internal.DeltaProtocolError: Atomic rename requires a LockClient for S3 backends. Either configure the LockClient, or set AWS_S3_ALLOW_UNSAFE_RENAME=true to opt out of support for concurrent writers.`

**Comment by roeap** [comment]
Did you configure the required headers as shown in the example above?

**Comment by djouallah** [comment]
I am using this, what should I change ?

```
storage_options = {
"Region": "us-east-1",   
"AWS_ACCESS_KEY_ID":  xxxxxxxxxxxxxxx,
"AWS_SECRET_ACCESS_KEY": yyyyyyyyyyyyyyyyyyyy   ,   
"AWS_ENDPOINT_URL" : xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx,
"AWS_S3_ALLOW_UNSAFE_RENAME":"true"
}
write_deltalake("s3://aemo/xvx", df,mode="append",storage_options=storage_options)
```

**Comment by roeap** [comment]
yes, the R2 support comes from object store and requires passing a speicific header value to the underlying service. Personally I never used it, but it seems cmacenzie1 did.

hopefully something like this works. 

```py
storage_options = {
    "region": "us-east-1",   
    "access_key_id":  "key",
    "secret_access_key": "secret",   
    "endpoint_url" : "url",
    "copy_if_not_exists": "header: cf-copy-destination-if-none-match: *"
}
```

**Comment by djouallah** [comment]
Thank you, it seems to be working :) have a great day

**Comment by djouallah** [comment]
do you think this section should be updated ?
![image](https://github.com/delta-io/delta-rs/assets/12554469/cc2b9c5a-c0f1-4af5-bff9-915f0e4bfa27)
